project_name: newrelic_exporter
release:
  github:
    owner: ContaAzul
    name: newrelic_exporter
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
- name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
changelog:
  filters:
    exclude:
    - '^Merge (remote|branch|pull)'
dockers:
- image_templates:
  - 'caninjas/newrelic_exporter:{{ .Tag }}'
  - 'caninjas/newrelic_exporter:v{{ .Major }}'
  - 'caninjas/newrelic_exporter:v{{ .Major }}.{{ .Minor }}'
  - 'caninjas/newrelic_exporter:latest'
